# Generated by Django 5.1.3 on 2024-11-19 11:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EnergyData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(upload_to='uploads/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ceiling_kwh', models.FloatField(help_text='Quarterly energy ceiling in KWH')),
                ('high_price_start', models.TimeField()),
                ('high_price_end', models.TimeField()),
                ('price_high', models.DecimalField(decimal_places=2, max_digits=6)),
                ('price_low', models.DecimalField(decimal_places=2, max_digits=6)),
                ('solar_return_high', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('solar_return_low', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('has_solar', models.BooleanField(default=False)),
                ('solar_setup_type', models.CharField(blank=True, max_length=50, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
